name: Build
on:
  push:
    branches:
    - main
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - closed
    branches:
    - main
env:
  IS_RELEASE_CANDIDATE: >-
    ${{
      (
        github.event_name == 'pull_request' &&
        startsWith(github.event.pull_request.title, 'RELEASES:') &&
        contains(github.event.pull_request.labels.*.name, 'RELEASES')
      )
      ||
      (
        github.event_name == 'push' &&
        startsWith(github.event.head_commit.message, 'RELEASES:') &&
        github.ref_name == 'RELEASE'
      )
    }}
jobs:
  build:
    runs-on: windows-latest
    env:
      NEL_MESH_CLIENT_ACCEPTANCE_MESHCONFIGURATION__MAILBOXID: ${{ secrets.NEL_MESH_CLIENT_ACCEPTANCE_MESHCONFIGURATION__MAILBOXID }}
      NEL_MESH_CLIENT_ACCEPTANCE_MESHCONFIGURATION__PASSWORD: ${{ secrets.NEL_MESH_CLIENT_ACCEPTANCE_MESHCONFIGURATION__PASSWORD }}
      NEL_MESH_CLIENT_ACCEPTANCE_MESHCONFIGURATION__KEY: ${{ secrets.NEL_MESH_CLIENT_ACCEPTANCE_MESHCONFIGURATION__KEY }}
      NEL_MESH_CLIENT_ACCEPTANCE_MESHCONFIGURATION__ROOTCERTIFICATE: ${{ secrets.NEL_MESH_CLIENT_ACCEPTANCE_MESHCONFIGURATION__ROOTCERTIFICATE }}
      NEL_MESH_CLIENT_ACCEPTANCE_MESHCONFIGURATION__INTERMEDIATECERTIFICATES__0: ${{ secrets.NEL_MESH_CLIENT_ACCEPTANCE_MESHCONFIGURATION__INTERMEDIATECERTIFICATES__0 }}
      NEL_MESH_CLIENT_ACCEPTANCE_MESHCONFIGURATION__CLIENTCERTIFICATE: ${{ secrets.NEL_MESH_CLIENT_ACCEPTANCE_MESHCONFIGURATION__CLIENTCERTIFICATE }}
      NEL_MESH_CLIENT_INTEGRATION_MESHCONFIGURATION__MAILBOXID: ${{ secrets.NEL_MESH_CLIENT_INTEGRATION_MESHCONFIGURATION__MAILBOXID }}
      NEL_MESH_CLIENT_INTEGRATION_MESHCONFIGURATION__PASSWORD: ${{ secrets.NEL_MESH_CLIENT_INTEGRATION_MESHCONFIGURATION__PASSWORD }}
      NEL_MESH_CLIENT_INTEGRATION_MESHCONFIGURATION__KEY: ${{ secrets.NEL_MESH_CLIENT_INTEGRATION_MESHCONFIGURATION__KEY }}
      NEL_MESH_CLIENT_INTEGRATION_MESHCONFIGURATION__ROOTCERTIFICATE: ${{ secrets.NEL_MESH_CLIENT_INTEGRATION_MESHCONFIGURATION__ROOTCERTIFICATE }}
      NEL_MESH_CLIENT_INTEGRATION_MESHCONFIGURATION__INTERMEDIATECERTIFICATES__0: ${{ secrets.NEL_MESH_CLIENT_INTEGRATION_MESHCONFIGURATION__INTERMEDIATECERTIFICATES__0 }}
      NEL_MESH_CLIENT_INTEGRATION_MESHCONFIGURATION__CLIENTCERTIFICATE: ${{ secrets.NEL_MESH_CLIENT_INTEGRATION_MESHCONFIGURATION__CLIENTCERTIFICATE }}
    steps:
    - name: Check Out
      uses: actions/checkout@v3
    - name: Setup Dot Net Version
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.201
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  add_tag:
    runs-on: ubuntu-latest
    needs:
    - build
    if: >
      github.event.pull_request.merged &&
      github.event.pull_request.base.ref == 'main' &&
      startsWith(github.event.pull_request.title, 'RELEASES:') &&
      contains(github.event.pull_request.labels.*.name, 'RELEASES')
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Extract Version Number
      id: extract_version
      run: |-
        echo "version_number=$(grep -oP '(?<=<Version>)[^<]+' NEL.MESH/NEL.MESH.csproj)" >> $GITHUB_OUTPUT
    - name: Print Version Number
      run: |-
        echo "Release version number is ${{ steps.extract_version.outputs.version_number }}"
    - name: Authenticate with GitHub
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_FOR_TAGGING }}
    - name: Configure Git
      run: |-
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
    - name: Generate Release Notes
      run: |-
        npm install -g conventional-changelog-cli
        npx conventional-changelog-cli -p angular -i CHANGELOG.md -s -r 0
    - name: Add Git Tag - Release
      run: |-
        git add CHANGELOG.md
        git commit -m "Update release notes"
        git tag -a "release-${{ steps.extract_version.outputs.version_number }}" -m "Release ${{ steps.extract_version.outputs.version_number }}"
        git push origin --tags
